# Pre-commit configuration.
# https://pre-commit.com

# pre-commit install
# pre-commit run --all-files

default_stages:
  - pre-commit
  - pre-push
  - commit-msg
  - manual

repos:
  # Fix some errors with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [ --fix, --exit-zero ]
        name: "ruff: fixing"
      - id: ruff-format
        name: "ruff: formatting"

  # Lint Python files with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        name: "ruff: linting"

  # Check other files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: alembic/
      - id: end-of-file-fixer
        exclude: alembic/
      - id: check-added-large-files

  # Generate settings.schema.yaml
  - repo: local
    hooks:
      - id: generate-settings-schema
        name: generate settings.schema.yaml
        language: system
        entry: poetry run python ./scripts/generate_settings_schema.py
        pass_filenames: false
        files: ^src/config_schema.py$
