# yaml-language-server: $schema=settings.schema.yaml
$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
db_url: null
accounts:
  # Get from https://api.innohassle.ru/accounts/v0/tokens/generate-service-token?sub=events-local-dev&scopes=users&only_for_me=true
  api_jwt_token: null
