# Check settings.schema.yaml for more details
$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
db_url: postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
accounts:
  # JWT secret
  api_jwt_token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
